### ISSUE TITLE
Build ABORTED if `gh` is not GitHub CLI

### ISSUE THREAD

**Issue by matt9ucci** [corvus-dotnet/Corvus.UriTemplates#26]
The build.ps1 fails:

```
ERROR: A positional parameter cannot be found that accepts argument 'view'.
At C:\XXXX\Endjin.RecommendedPractices.Build\1.1.0\import-tasks.ps1:13 char:15
+ $taskGroups | ForEach-Object {
+               ~~~~~~~~~~~~~~~~
Build ABORTED C:\XXXX\Corvus.UriTemplates\build.ps1. 0 tasks, 1 errors, 0 warnings 00:00:00.0979544
```

The result of `Get-Error` cmdlet as follows:

```
Message           : A positional parameter cannot be found that accepts argument 'view'.

...

PositionMessage  : At C:\XXXX\Endjin.RecommendedPractices.Build\1.1.0\tasks\analysis.tasks.ps1:5 char:72
                           + … ction SilentlyContinue) { & gh repo view --json nameWithOwner | Conve …
                           +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
						   
That is because I use `gh` as an alias and do not install GitHub CLI.

**Comment by JamesDawson** [comment]
Thanks for the report. We'll take a look at how we can handle this a bit more gracefully - in the meantime, if this is blocking you then setting `$SkipAnalysis` to `true` in `build.ps1` is a workaround.

**Comment by matt9ucci** [comment]
> setting `$SkipAnalysis` to `true` in `build.ps1` is a workaround.

Thank you for your reply, but it causes the same error.
My workaround is to temporarily remove the alias by `Remove-Alias gh` before executing `build.ps1`.

**Comment by JamesDawson** [comment]
Ah yes, of course, that all happens as initialisation rather than during the main part of the build - would you mind testing [this branch](/corvus-dotnet/Corvus.UriTemplates/tree/feature/bump-build-tooling) to see if it resolves your issue?  If it does then we'll get the PR merged.

**Comment by matt9ucci** [comment]
The `build.ps1` in [the branch](https://github.com/corvus-dotnet/Corvus.UriTemplates/tree/feature/bump-build-tooling) does not work.

case 1) When `gh` is an alias:
```
PS> Get-Error -Newest 2

Message : A positional parameter cannot be found that accepts argument 'view'.

PositionMessage  : At C:\XXXX\Endjin.RecommendedPractices.Build\1.1.1\tasks\analysis.tasks.ps1:7 char:23     
		   +             $ghRepo = & gh repo view --json nameWithOwner
		   +                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

case 2) After `Remove-Alias gh`:
```
PS> Get-Error -Newest 2

Message : The term 'gh' is not recognized as a name of a cmdlet, function, script file, or executable program.
          Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 
PositionMessage  : At C:\XXXX\Endjin.RecommendedPractices.Build\1.1.1\tasks\analysis.tasks.ps1:5 char:22
                   + …    git_repo = $(if (Get-Command "gh" -ErrorAction SilentlyContinue) {
                   +                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by matt9ucci** [comment]
[Both case 1 and 2](https://github.com/corvus-dotnet/Corvus.UriTemplates/issues/26#issuecomment-1328236418) cause the same error:
```
GitVersion Config: C:\XXXX\Corvus.UriTemplates/GitVersion.yml
ERROR: Command { dotnet-gitversion /output json /nofetch /config $GitVersionConfig } exited with code 1.
At C:\XXXX\Endjin.RecommendedPractices.Build\1.1.1\tasks\versioning.tasks.ps1:13 char:29
+ … utputJson = exec { dotnet-gitversion /output json /nofetch /config $G …
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by JamesDawson** [comment]
Ok, it's moved on - those `gh` errors should be silent/non-fatal now (albeit still visible to `Get-Error`).

I suspect this new error is a .Net SDK version mismatch issue related to the GitVersion global tool. What output do you get if you run the following from the root of the repo?

```
dotnet-gitversion
```

**Comment by matt9ucci** [comment]
The output:
```
PS> dotnet-gitversion

INFO [11/27/22 23:39:39:93] Working directory: C:\XXXX\Corvus.UriTemplates

...

  INFO [11/27/22 23:39:40:07] End: Attempting to inherit branch configuration from parent branch (Took: 19.93ms)
  ERROR [11/27/22 23:39:40:08] An unexpected error occurred:
System.InvalidOperationException: Gitversion could not determine which branch to treat as the development branch (default is 'develop') nor releaseable branch (default is 'main' or 'master'), either locally or remotely. Ensure the local clone and checkout match the requirements or considering using 'GitVersion Dynamic Repositories'
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 134
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 44
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 39
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 51
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
  INFO [11/27/22 23:39:40:08] Attempting to show the current git graph (please include in issue):
  INFO [11/27/22 23:39:40:08] Showing max of 100 commits
  INFO [11/27/22 23:39:40:13] * b131673 3 hours ago  (HEAD -> feature/bump-build-tooling, origin/feature/bump-build-tooling)
| * 2f66a34 2 days ago  (origin/dependabot/nuget/Solutions/Endjin.RecommendedPractices.GitHub-2.1.3)
|/
* cf33eb0 3 days ago  (origin/main, origin/HEAD)
| * bcdfae1 4 days ago  (origin/dependjinbot/scripted-build-manage)

...

```
```
PS> dotnet-gitversion /version
5.8.0+Branch.main.Sha.9acbfb1d6a83c490453ae2a6948c15e0fa81b9fd
```
```
PS> dotnet --version
7.0.100
```

**Comment by matt9ucci** [comment]
```
PS> $PSVersionTable | select PSVersion, Platform

PSVersion Platform
--------- --------
7.3.0     Win32NT
```

**Comment by JamesDawson** [comment]
This gets more interesting 🙂.  Do you have a full or shallow clone of the repo?  If you do have a full clone, then does GitVersion give different output with the full command used in the build? (again run from the root of the repo)

```
dotnet-gitversion /output json /nofetch /config ./GitVersion.yml
```

**Comment by matt9ucci** [comment]
I tried it again and got "Build succeeded" message. Thank you so much. (Last night, I did `git clone` only the `feature/bump-build-tooling` branch.)

Also, `dotnet-gitversion` succeeded at this time:

```
PS> dotnet-gitversion /output json /nofetch /config ./GitVersion.yml
{
  "Major": 1,
  "Minor": 0,
  "Patch": 2,
  "PreReleaseTag": "bump-build-tooling.2",
  "PreReleaseTagWithDash": "-bump-build-tooling.2",
  "PreReleaseLabel": "bump-build-tooling",
  "PreReleaseLabelWithDash": "-bump-build-tooling",
  "PreReleaseNumber": 2,
  "WeightedPreReleaseNumber": 30002,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.feature-bump-build-tooling.Sha.1e29f6de10bf6ef9f79e12d918d437f0deda534d",
  "MajorMinorPatch": "1.0.2",
  "SemVer": "1.0.2-bump-build-tooling.2",
  "LegacySemVer": "1.0.2-bump-build-tooling2",
  "LegacySemVerPadded": "1.0.2-bump-build-tooli0002",
  "AssemblySemVer": "1.0.2.0",
  "AssemblySemFileVer": "1.0.2.0",
  "FullSemVer": "1.0.2-bump-build-tooling.2",
  "InformationalVersion": "1.0.2-bump-build-tooling.2+Branch.feature-bump-build-tooling.Sha.1e29f6de10bf6ef9f79e12d918d437f0deda534d",
  "BranchName": "feature/bump-build-tooling",
  "EscapedBranchName": "feature-bump-build-tooling",
  "Sha": "1e29f6de10bf6ef9f79e12d918d437f0deda534d",
  "ShortSha": "1e29f6d",
  "NuGetVersionV2": "1.0.2-bump-build-tooli0002",
  "NuGetVersion": "1.0.2-bump-build-tooli0002",
  "NuGetPreReleaseTagV2": "bump-build-tooli0002",
  "NuGetPreReleaseTag": "bump-build-tooli0002",
  "VersionSourceSha": "a123ad5bdee0d4011be3fc6952901102a3b4ba0d",
  "CommitsSinceVersionSource": 2,
  "CommitsSinceVersionSourcePadded": "0002",
  "UncommittedChanges": 0,
  "CommitDate": "2022-11-28"
}
```

**Comment by JamesDawson** [comment]
That's great, thanks for letting us know - we'll merge that PR now.
